### ISSUE TITLE
Kompiliert nicht ohne fontaxes

### ISSUE THREAD

**Issue by nimius-dev** [JaMeZ-B/template_bachelor_thesis_wwu#2]
Kompiliert auf meinem System nicht ohne `\usepackage{fontaxes}` in `preamble.tex`

Systeminformationen:
AMD64 Arch Linux, tagesaktuell
linux-zen 6.2.2.zen1-1
texlive-core 2022.63035-1
texlive-bin 2022.62885-5

Ich mache einen PR falls du das einfügen möchtest.

Ansonsten noch vielen Dank für die schöne und praktische Vorlage :^)

**Comment by jannes-bantje** [comment]
Schön, wenn auch mal in einem 8 Jahre alten Repo was passiert 😄 

Das Problem kann ich nicht reproduzieren (TeXlive frisch geupdated). Könntest du mir die tatsächlich Fehlermeldung schicken? Am besten auch noch den Output von `latex --version` (weil ich bei TeX-Installationen über Paketmanager immer etwas skeptisch bin, was die Aktualität angeht) 

Das Paket `fontaxes` kannte ich bis eben gar nicht und mir ist nicht klar, warum dieses Dokument es benötigen sollte – insbesondere fixt es ja nichts, sondern erweitert nur das Font Selection Schema.

**Comment by nimius-dev** [comment]
In den Arch-Repos ist alles immer aktuell (manchmal zu aktuell)
```
❯ latex --version
pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022/Arch Linux)
kpathsea version 6.3.4
Copyright 2022 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.39; using libpng 1.6.39
Compiled with zlib 1.2.13; using zlib 1.2.13
Compiled with xpdf version 4.03
```

Allerdings kann ich den Fehler nun auch nicht mehr reproduzieren... lag möglicherweise Updates ohne Neustart, aber nun kompiliert die Datei ohne diesen Fehler.  War also wohl ein Fehler auf meiner Seite, sorry dafür :grin:
